import type { Listing, Post } from './types';

const avatar = (seed: string) =>
  `https://api.dicebear.com/7.x/initials/svg?backgroundColor=3b6cf5,10b981,f98c07,8b5cf6,ef4444&textColor=ffffff&seed=${encodeURIComponent(
    seed,
  )}`;
export const POSTS: Post[] = [
  {
    id: 'gmp1',
    user: {
      name: 'Mumbai Motor Bazaar',
      handle: '@mumbaimotorbazaar',
      avatar: avatar('Mumbai Motor Bazaar'),
    },
    image: '/images/bikes/royal-enfield-classic-350.jpg',
    caption: 'Picked up this Royal Enfield Classic 350. Smooth ride, iconic thump, and fully serviced!',
    category: 'Bikes',
    likes: 512,
    liked: true,
    saved: false,
    createdAt: '2024-09-21T15:20:00Z',
    comments: [
      {
        id: 'gmc11',
        user: 'Bike Lovers India',
        avatar: avatar('Bike Lovers India'),
        text: 'Classic never goes out of style!',
        createdAt: '2024-09-21T17:10:00Z',
      },
      {
        id: 'gmc12',
        user: 'Rahul S.',
        avatar: avatar('Rahul S.'),
        text: 'Looks absolutely clean!',
        createdAt: '2024-09-21T18:45:00Z',
      },
    ],
  },
  {
    id: 'gmp2',
    user: {
      name: 'Chandigarh Wheels',
      handle: '@chandigarhwheels',
      avatar: avatar('Chandigarh Wheels'),
    },
    image: '/images/bikes/bajaj-pulsar-ns200.jpg',
    caption: 'Just listed this Bajaj Pulsar NS200 with ABS. Engine runs perfectly and is well maintained.',
    category: 'Bikes',
    likes: 389,
    liked: false,
    saved: true,
    createdAt: '2024-09-26T22:10:00Z',
    comments: [
      {
        id: 'gmc21',
        user: 'MotorHub',
        avatar: avatar('MotorHub'),
        text: 'Great bike for the price!',
        createdAt: '2024-09-27T09:15:00Z',
      },
    ],
  },
  {
    id: 'gmp3',
    user: {
      name: 'Ahmedabad Tech Store',
      handle: '@ahmedabadtech',
      avatar: avatar('Ahmedabad Tech Store'),
    },
    image: '/images/bikes/honda-activa-6g.jpg',
    caption: 'Honda Activa 6G with low mileage and new battery. Perfect for daily commuting.',
    category: 'Bikes',
    likes: 274,
    liked: true,
    saved: false,
    createdAt: '2024-06-01T17:30:00Z',
    comments: [
      {
        id: 'gmc31',
        user: 'Daily Riders',
        avatar: avatar('Daily Riders'),
        text: 'Excellent city scooter!',
        createdAt: '2024-06-02T08:00:00Z',
      },
    ],
  },
  {
    id: 'gmp4',
    user: {
      name: 'Kolkata Shoe Gallery',
      handle: '@kolkatashoes',
      avatar: avatar('Kolkata Shoe Gallery'),
    },
    image: '/images/bikes/tvs-apache-rtr-160.jpg',
    caption: 'TVS Apache RTR 160 in great condition with fully functional digital console.',
    category: 'Bikes',
    likes: 198,
    liked: false,
    saved: false,
    createdAt: '2024-07-26T13:10:00Z',
    comments: [
      {
        id: 'gmc41',
        user: 'Speed Riders',
        avatar: avatar('Speed Riders'),
        text: 'Apache looks fantastic!',
        createdAt: '2024-07-26T16:00:00Z',
      },
    ],
  },
  {
    id: 'gmp5',
    user: {
      name: 'Surat Diamond Traders',
      handle: '@suratdiamond',
      avatar: avatar('Surat Diamond Traders'),
    },
    image: '/images/bikes/yamaha-fz-s-v3.jpg',
    caption: 'Reliable Yamaha FZ-S V3 with smooth gear shifts and great mileage.',
    category: 'Bikes',
    likes: 425,
    liked: true,
    saved: true,
    createdAt: '2024-09-24T19:30:00Z',
    comments: [
      {
        id: 'gmc51',
        user: 'FZ Riders Club',
        avatar: avatar('FZ Riders Club'),
        text: 'Love this generation of FZ!',
        createdAt: '2024-09-25T08:00:00Z',
      },
    ],
  },
  {
    id: 'gmp6',
    user: {
      name: 'Jaipur Realty Partners',
      handle: '@jaipurrealty',
      avatar: avatar('Jaipur Realty Partners'),
    },
    image: '/images/bikes/hero-splendor-plus.jpg',
    caption: 'Hero Splendor Plus—budget-friendly, reliable, and perfect for everyday rides.',
    category: 'Bikes',
    likes: 316,
    liked: false,
    saved: true,
    createdAt: '2024-08-18T21:45:00Z',
    comments: [
      {
        id: 'gmc61',
        user: 'Commuter Club',
        avatar: avatar('Commuter Club'),
        text: 'Mileage king!',
        createdAt: '2024-08-19T09:20:00Z',
      },
    ],
  },
  {
    id: 'gmp7',
    user: {
      name: 'Delhi Wheels & More',
      handle: '@delhiwheels',
      avatar: avatar('Delhi Wheels & More'),
    },
    image: '/images/bikes/ktm-duke-200.jpg',
    caption: 'KTM Duke 200 with upgraded exhaust and enthusiast-owned condition.',
    category: 'Bikes',
    likes: 691,
    liked: true,
    saved: false,
    createdAt: '2024-06-05T08:00:00Z',
    comments: [
      {
        id: 'gmc71',
        user: 'Orange Army',
        avatar: avatar('Orange Army'),
        text: 'Ready to race!',
        createdAt: '2024-06-05T11:15:00Z',
      },
      {
        id: 'gmc72',
        user: 'Amit',
        avatar: avatar('Amit'),
        text: 'Looks brand new.',
        createdAt: '2024-06-05T13:00:00Z',
      },
    ],
  },
  {
    id: 'gmp8',
    user: {
      name: 'Noida Property Desk',
      handle: '@noidaproperty',
      avatar: avatar('Noida Property Desk'),
    },
    image: '/images/bikes/suzuki-access-125.jpg',
    caption: 'Suzuki Access 125 with spacious storage and a super smooth ride.',
    category: 'Bikes',
    likes: 244,
    liked: false,
    saved: false,
    createdAt: '2024-09-06T16:20:00Z',
    comments: [
      {
        id: 'gmc81',
        user: 'Scooter Lovers',
        avatar: avatar('Scooter Lovers'),
        text: 'Best scooter for families.',
        createdAt: '2024-09-06T18:00:00Z',
      },
    ],
  },
  {
    id: 'gmp9',
    user: {
      name: 'Jaipur Realty Partners',
      handle: '@jaipurrealty',
      avatar: avatar('Jaipur Realty Partners'),
    },
    image: '/images/cars/maruti-suzuki-swift-vxi.jpg',
    caption: 'Maruti Suzuki Swift VXI with alloy wheels and complete service history.',
    category: 'Cars',
    likes: 587,
    liked: true,
    saved: true,
    createdAt: '2024-07-22T07:20:00Z',
    comments: [
      {
        id: 'gmc91',
        user: 'Swift Owners',
        avatar: avatar('Swift Owners'),
        text: 'Looks very well maintained!',
        createdAt: '2024-07-22T10:00:00Z',
      },
    ],
  },
  {
    id: 'gmp10',
    user: {
      name: 'Chandigarh Wheels',
      handle: '@chandigarhwheels',
      avatar: avatar('Chandigarh Wheels'),
    },
    image: '/images/cars/hyundai-creta-sx.jpg',
    caption: 'Hyundai Creta SX loaded with sunroof, ventilated seats, and premium features.',
    category: 'Cars',
    likes: 743,
    liked: true,
    saved: false,
    createdAt: '2024-06-25T12:10:00Z',
    comments: [
      {
        id: 'gmc101',
        user: 'Car Enthusiasts',
        avatar: avatar('Car Enthusiasts'),
        text: 'Creta is always a solid choice!',
        createdAt: '2024-06-25T15:30:00Z',
      },
      {
        id: 'gmc102',
        user: 'Rohit',
        avatar: avatar('Rohit'),
        text: 'Interior looks amazing.',
        createdAt: '2024-06-25T17:00:00Z',
      },
    ],
  },
];
export const LISTINGS: Listing[] = [
  {
    id: 'gm1',
    title: 'Royal Enfield Classic 350',
    category: 'Bikes',
    condition: 'Excellent',
    price: 185000,
    image: '/images/bikes/royal-enfield-classic-350.jpg',
    seller: 'Mumbai Motor Bazaar',
    location: 'Mumbai, MH',
    createdAt: '2024-09-21T15:20:00Z',
    description:
      'Single-owner Royal Enfield Classic 350 with full service history and recent tyre change. Smooth thump, no mechanical issues.',
  },
  {
    id: 'gm2',
    title: 'Bajaj Pulsar NS200',
    category: 'Bikes',
    condition: 'Good',
    price: 95000,
    image: '/images/bikes/bajaj-pulsar-ns200.jpg',
    seller: 'Chandigarh Wheels',
    location: 'Chandigarh, CH',
    createdAt: '2024-09-26T22:10:00Z',
    description:
      'Well-maintained Pulsar NS200 with ABS, minor scratches on the tank, engine runs perfectly.',
  },
  {
    id: 'gm3',
    title: 'Honda Activa 6G',
    category: 'Bikes',
    condition: 'Excellent',
    price: 95000,
    image: '/images/bikes/honda-activa-6g.jpg',
    seller: 'Ahmedabad Tech Store',
    location: 'Ahmedabad, GJ',
    createdAt: '2024-06-01T17:30:00Z',
    description:
      'Low mileage Activa 6G, ideal city commuter, recently serviced with new battery.',
  },
  {
    id: 'gm4',
    title: 'TVS Apache RTR 160',
    category: 'Bikes',
    condition: 'Fine',
    price: 65000,
    image: '/images/bikes/tvs-apache-rtr-160.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-07-26T13:10:00Z',
    description:
      'Sporty Apache RTR 160 in good working condition, digital console fully functional.',
  },
  {
    id: 'gm5',
    title: 'Yamaha FZ-S V3',
    category: 'Bikes',
    condition: 'Good',
    price: 45000,
    image: '/images/bikes/yamaha-fz-s-v3.jpg',
    seller: 'Surat Diamond Traders',
    location: 'Surat, GJ',
    createdAt: '2024-09-24T19:30:00Z',
    description:
      'Reliable FZ-S with smooth gear shifts, decent mileage, comes with helmet and cover.',
  },
  {
    id: 'gm6',
    title: 'Hero Splendor Plus',
    category: 'Bikes',
    condition: 'Fair',
    price: 45000,
    image: '/images/bikes/hero-splendor-plus.jpg',
    seller: 'Jaipur Realty Partners',
    location: 'Jaipur, RJ',
    createdAt: '2024-08-18T21:45:00Z',
    description:
      'Budget-friendly daily commuter, runs well, some cosmetic wear on the body panels.',
  },
  {
    id: 'gm7',
    title: 'KTM Duke 200',
    category: 'Bikes',
    condition: 'Excellent',
    price: 150000,
    image: '/images/bikes/ktm-duke-200.jpg',
    seller: 'Delhi Wheels & More',
    location: 'New Delhi, DL',
    createdAt: '2024-06-05T08:00:00Z',
    description:
      'Adrenaline-ready KTM Duke 200, upgraded exhaust, well cared for by enthusiast owner.',
  },
  {
    id: 'gm8',
    title: 'Suzuki Access 125',
    category: 'Bikes',
    condition: 'Good',
    price: 45000,
    image: '/images/bikes/suzuki-access-125.jpg',
    seller: 'Noida Property Desk',
    location: 'Noida, UP',
    createdAt: '2024-09-06T16:20:00Z',
    description:
      'Comfortable Access 125 scooter, spacious under-seat storage, smooth ride quality.',
  },
  {
    id: 'gm9',
    title: 'Maruti Suzuki Swift VXI',
    category: 'Cars',
    condition: 'Excellent',
    price: 650000,
    image: '/images/cars/maruti-suzuki-swift-vxi.jpg',
    seller: 'Jaipur Realty Partners',
    location: 'Jaipur, RJ',
    createdAt: '2024-07-22T07:20:00Z',
    description:
      'Single-owner Swift VXI with complete service records, no accident history, alloy wheels.',
  },
  {
    id: 'gm10',
    title: 'Hyundai Creta SX',
    category: 'Cars',
    condition: 'Fine',
    price: 780000,
    image: '/images/cars/hyundai-creta-sx.jpg',
    seller: 'Chandigarh Wheels',
    location: 'Chandigarh, CH',
    createdAt: '2024-06-25T12:10:00Z',
    description:
      'Feature-loaded Creta SX with sunroof, ventilated seats, and updated infotainment.',
  },
  {
    id: 'gm11',
    title: 'Tata Nexon XZ+',
    category: 'Cars',
    condition: 'Good',
    price: 520000,
    image: '/images/cars/tata-nexon-xz.jpg',
    seller: 'Kochi Jewels & Gems',
    location: 'Kochi, KL',
    createdAt: '2024-06-18T21:30:00Z',
    description:
      '5-star safety rated Nexon XZ+, well maintained with recent brake service.',
  },
  {
    id: 'gm12',
    title: 'Mahindra XUV700 AX7',
    category: 'Cars',
    condition: 'Excellent',
    price: 1350000,
    image: '/images/cars/mahindra-xuv700-ax7.jpg',
    seller: 'Chandigarh Wheels',
    location: 'Chandigarh, CH',
    createdAt: '2024-07-11T10:30:00Z',
    description:
      'Top-spec XUV700 with ADAS features, panoramic sunroof, and premium sound system.',
  },
  {
    id: 'gm13',
    title: 'Honda City ZX',
    category: 'Cars',
    condition: 'Good',
    price: 950000,
    image: '/images/cars/honda-city-zx.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-08-15T22:20:00Z',
    description:
      'Comfortable sedan with smooth automatic transmission, regularly serviced at authorized center.',
  },
  {
    id: 'gm14',
    title: 'Toyota Innova Crysta',
    category: 'Cars',
    condition: 'Fine',
    price: 1650000,
    image: '/images/cars/toyota-innova-crysta.jpg',
    seller: 'Pune Mobile World',
    location: 'Pune, MH',
    createdAt: '2024-09-09T06:00:00Z',
    description:
      'Spacious 7-seater Innova Crysta, ideal for family trips, diesel engine runs strong.',
  },
  {
    id: 'gm15',
    title: 'Kia Seltos GTX+',
    category: 'Cars',
    condition: 'Excellent',
    price: 1650000,
    image: '/images/cars/kia-seltos-gtx.jpg',
    seller: 'Mumbai Motor Bazaar',
    location: 'Mumbai, MH',
    createdAt: '2024-06-16T08:30:00Z',
    description:
      'Loaded Seltos GTX+ with turbo engine, premium interiors, single owner.',
  },
  {
    id: 'gm16',
    title: 'Maruti Suzuki Baleno Zeta',
    category: 'Cars',
    condition: 'Good',
    price: 2200000,
    image: '/images/cars/maruti-suzuki-baleno-zeta.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-07-19T16:30:00Z',
    description:
      'Fuel-efficient Baleno Zeta with touchscreen infotainment, well-kept interiors.',
  },
  {
    id: 'gm17',
    title: '22K Gold Necklace Set — Tanishq Design',
    category: 'Jewellery',
    condition: 'Excellent',
    price: 15000,
    image: '/images/jewellery/22k-gold-necklace-set-tanishq-design.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-07-22T11:45:00Z',
    description:
      'Elegant 22K gold necklace set with matching earrings, hallmark certified, barely worn.',
  },
  {
    id: 'gm18',
    title: 'Diamond Solitaire Engagement Ring',
    category: 'Jewellery',
    condition: 'Mint',
    price: 65000,
    image: '/images/jewellery/diamond-solitaire-engagement-ring.jpg',
    seller: 'Pune Mobile World',
    location: 'Pune, MH',
    createdAt: '2024-08-25T15:10:00Z',
    description:
      'Certified diamond solitaire ring in 18K white gold setting, comes with original certification.',
  },
  {
    id: 'gm19',
    title: 'Platinum Wedding Band Pair',
    category: 'Jewellery',
    condition: 'Excellent',
    price: 22000,
    image: '/images/jewellery/platinum-wedding-band-pair.jpg',
    seller: 'Delhi Wheels & More',
    location: 'New Delhi, DL',
    createdAt: '2024-06-27T11:20:00Z',
    description:
      'Matching platinum wedding bands, brushed finish, hallmark certified with warranty card.',
  },
  {
    id: 'gm20',
    title: 'Gold Bangles Set, 4 Piece',
    category: 'Jewellery',
    condition: 'Fine',
    price: 22000,
    image: '/images/jewellery/gold-bangles-set-4-piece.jpg',
    seller: 'Pune Mobile World',
    location: 'Pune, MH',
    createdAt: '2024-06-22T22:45:00Z',
    description:
      'Traditional gold bangles with intricate engraving, ideal for weddings and festive occasions.',
  },
  {
    id: 'gm21',
    title: 'CaratLane Diamond Earrings',
    category: 'Jewellery',
    condition: 'Mint',
    price: 89000,
    image: '/images/jewellery/caratlane-diamond-earrings.jpg',
    seller: 'Chennai Gold House',
    location: 'Chennai, TN',
    createdAt: '2024-07-24T06:15:00Z',
    description:
      'Delicate diamond stud earrings in rose gold, purchased recently with unused warranty.',
  },
  {
    id: 'gm22',
    title: 'Antique Kundan Choker Necklace',
    category: 'Jewellery',
    condition: 'Good',
    price: 89000,
    image: '/images/jewellery/antique-kundan-choker-necklace.jpg',
    seller: 'Jaipur Realty Partners',
    location: 'Jaipur, RJ',
    createdAt: '2024-07-08T11:30:00Z',
    description:
      'Statement Kundan choker with uncut diamonds, perfect for bridal wear.',
  },
  {
    id: 'gm23',
    title: 'Pearl and Gold Mangalsutra',
    category: 'Jewellery',
    condition: 'Excellent',
    price: 125000,
    image: '/images/jewellery/pearl-and-gold-mangalsutra.jpg',
    seller: 'Delhi Wheels & More',
    location: 'New Delhi, DL',
    createdAt: '2024-09-25T21:00:00Z',
    description:
      'Classic mangalsutra design with black beads and gold pendant, lightly worn.',
  },
  {
    id: 'gm24',
    title: 'Samsung Crystal 4K UHD Smart TV 55"',
    category: 'Electronics',
    condition: 'Excellent',
    price: 45000,
    image: '/images/electronics/samsung-crystal-4k-uhd-smart-tv-55.jpg',
    seller: 'Chandigarh Wheels',
    location: 'Chandigarh, CH',
    createdAt: '2024-06-28T14:45:00Z',
    description:
      'Barely used 55-inch 4K Smart TV with vibrant display and built-in streaming apps.',
  },
  {
    id: 'gm25',
    title: 'LG OLED C3 65" TV',
    category: 'Electronics',
    condition: 'Mint',
    price: 12000,
    image: '/images/electronics/lg-oled-c3-65-tv.jpg',
    seller: 'Hyderabad Electronics Hub',
    location: 'Hyderabad, TS',
    createdAt: '2024-09-08T11:20:00Z',
    description:
      'Premium OLED display with perfect blacks, includes Magic Remote and original packaging.',
  },
  {
    id: 'gm26',
    title: 'Sony Bravia 43" Full HD TV',
    category: 'Electronics',
    condition: 'Good',
    price: 55000,
    image: '/images/electronics/sony-bravia-43-full-hd-tv.jpg',
    seller: 'Delhi Wheels & More',
    location: 'New Delhi, DL',
    createdAt: '2024-07-05T21:00:00Z',
    description:
      'Reliable Sony Bravia TV, great for everyday viewing, all ports functional.',
  },
  {
    id: 'gm27',
    title: 'Mi TV 5X 50" 4K',
    category: 'Electronics',
    condition: 'Fine',
    price: 25000,
    image: '/images/electronics/mi-tv-5x-50-4k.jpg',
    seller: 'Hyderabad Electronics Hub',
    location: 'Hyderabad, TS',
    createdAt: '2024-10-24T21:00:00Z',
    description:
      'Budget-friendly 4K Smart TV with Android TV interface, works flawlessly.',
  },
  {
    id: 'gm28',
    title: 'Sony PlayStation 5 Console',
    category: 'Electronics',
    condition: 'Excellent',
    price: 55000,
    image: '/images/electronics/sony-playstation-5-console.jpg',
    seller: 'Chennai Gold House',
    location: 'Chennai, TN',
    createdAt: '2024-07-12T19:20:00Z',
    description:
      'PS5 console with two controllers and three games, barely used, all original accessories.',
  },
  {
    id: 'gm29',
    title: 'JBL Bar 5.1 Soundbar System',
    category: 'Electronics',
    condition: 'Excellent',
    price: 85000,
    image: '/images/electronics/jbl-bar-5-1-soundbar-system.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-08-05T14:10:00Z',
    description:
      'Immersive home theater soundbar with wireless subwoofer, includes remote and cables.',
  },
  {
    id: 'gm30',
    title: 'Dell XPS 15 Laptop',
    category: 'Electronics',
    condition: 'Fine',
    price: 12000,
    image: '/images/electronics/dell-xps-15-laptop.jpg',
    seller: 'Noida Property Desk',
    location: 'Noida, UP',
    createdAt: '2024-09-22T10:45:00Z',
    description:
      'Powerful XPS 15 with i7 processor, 16GB RAM, ideal for work and creative tasks.',
  },
  {
    id: 'gm31',
    title: 'Apple MacBook Air M2',
    category: 'Electronics',
    condition: 'Mint',
    price: 45000,
    image: '/images/electronics/apple-macbook-air-m2.jpg',
    seller: 'Bangalore Auto Traders',
    location: 'Bangalore, KA',
    createdAt: '2024-10-11T13:30:00Z',
    description:
      'Lightly used MacBook Air M2, excellent battery life, comes with original charger and box.',
  },
  {
    id: 'gm32',
    title: 'iPhone 15 Pro Max 256GB',
    category: 'Mobile Phones',
    condition: 'Mint',
    price: 55000,
    image: '/images/mobile-phones/iphone-15-pro-max-256gb.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-09-25T10:10:00Z',
    description:
      'Barely used iPhone 15 Pro Max in Titanium Blue, comes with box, charger, and case.',
  },
  {
    id: 'gm33',
    title: 'Samsung Galaxy S24 Ultra',
    category: 'Mobile Phones',
    condition: 'Excellent',
    price: 25000,
    image: '/images/mobile-phones/samsung-galaxy-s24-ultra.jpg',
    seller: 'Mumbai Motor Bazaar',
    location: 'Mumbai, MH',
    createdAt: '2024-09-04T11:00:00Z',
    description:
      'Flagship Galaxy S24 Ultra with S Pen, no scratches, screen protector applied since day one.',
  },
  {
    id: 'gm34',
    title: 'OnePlus 12 5G 256GB',
    category: 'Mobile Phones',
    condition: 'Fine',
    price: 95000,
    image: '/images/mobile-phones/oneplus-12-5g-256gb.jpg',
    seller: 'Kochi Jewels & Gems',
    location: 'Kochi, KL',
    createdAt: '2024-07-03T09:45:00Z',
    description:
      'Fast and reliable OnePlus 12 with Hasselblad camera system, minor wear on frame.',
  },
  {
    id: 'gm35',
    title: 'Xiaomi 14 Ultra',
    category: 'Mobile Phones',
    condition: 'Good',
    price: 32000,
    image: '/images/mobile-phones/xiaomi-14-ultra.jpg',
    seller: 'Hyderabad Electronics Hub',
    location: 'Hyderabad, TS',
    createdAt: '2024-08-18T16:20:00Z',
    description:
      'Camera-focused Xiaomi 14 Ultra, well maintained, includes original earphones.',
  },
  {
    id: 'gm36',
    title: 'Google Pixel 8 Pro',
    category: 'Mobile Phones',
    condition: 'Excellent',
    price: 42000,
    image: '/images/mobile-phones/google-pixel-8-pro.jpg',
    seller: 'Jaipur Realty Partners',
    location: 'Jaipur, RJ',
    createdAt: '2024-10-06T11:10:00Z',
    description:
      'Clean Android experience with excellent camera, includes charger and case.',
  },
  {
    id: 'gm37',
    title: 'Vivo V30 Pro',
    category: 'Mobile Phones',
    condition: 'Fine',
    price: 78000,
    image: '/images/mobile-phones/vivo-v30-pro.jpg',
    seller: 'Chandigarh Wheels',
    location: 'Chandigarh, CH',
    createdAt: '2024-07-23T07:30:00Z',
    description:
      'Stylish mid-range flagship with great portrait camera, lightly used with case always on.',
  },
  {
    id: 'gm38',
    title: 'Oppo Reno 11 Pro',
    category: 'Mobile Phones',
    condition: 'Good',
    price: 18000,
    image: '/images/mobile-phones/oppo-reno-11-pro.jpg',
    seller: 'Surat Diamond Traders',
    location: 'Surat, GJ',
    createdAt: '2024-06-13T20:00:00Z',
    description:
      'Sleek design with fast charging support, minor scuffs on the back panel.',
  },
  {
    id: 'gm39',
    title: 'Nike Air Jordan 1 Retro High',
    category: 'Shoes',
    condition: 'Excellent',
    price: 8900,
    image: '/images/shoes/nike-air-jordan-1-retro-high.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-10-06T13:15:00Z',
    description:
      'Iconic Jordan 1 colorway, worn a handful of times, original box included.',
  },
  {
    id: 'gm40',
    title: 'Adidas Ultraboost 22',
    category: 'Shoes',
    condition: 'Fine',
    price: 5800,
    image: '/images/shoes/adidas-ultraboost-22.jpg',
    seller: 'Surat Diamond Traders',
    location: 'Surat, GJ',
    createdAt: '2024-08-24T07:10:00Z',
    description:
      'Comfortable running shoes with responsive cushioning, good tread remaining.',
  },
  {
    id: 'gm41',
    title: 'Puma RS-X Sneakers',
    category: 'Shoes',
    condition: 'Good',
    price: 2500,
    image: '/images/shoes/puma-rs-x-sneakers.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-08-24T15:30:00Z',
    description:
      'Bold retro-style sneakers, minor sole wear, great for casual everyday use.',
  },
  {
    id: 'gm42',
    title: 'Bata Formal Leather Shoes',
    category: 'Shoes',
    condition: 'Excellent',
    price: 5800,
    image: '/images/shoes/bata-formal-leather-shoes.jpg',
    seller: 'Noida Property Desk',
    location: 'Noida, UP',
    createdAt: '2024-09-19T09:30:00Z',
    description:
      'Classic formal leather shoes, polished and well cared for, ideal for office wear.',
  },
  {
    id: 'gm43',
    title: 'Woodland Trekking Boots',
    category: 'Shoes',
    condition: 'Good',
    price: 1800,
    image: '/images/shoes/woodland-trekking-boots.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-10-20T16:30:00Z',
    description:
      'Durable outdoor boots with strong grip, shows some trail wear but structurally solid.',
  },
  {
    id: 'gm44',
    title: 'Reebok Classic Leather Sneakers',
    category: 'Shoes',
    condition: 'Fine',
    price: 3200,
    image: '/images/shoes/reebok-classic-leather-sneakers.jpg',
    seller: 'Hyderabad Electronics Hub',
    location: 'Hyderabad, TS',
    createdAt: '2024-10-17T12:00:00Z',
    description:
      'Timeless white sneakers, lightly worn, easy to pair with any outfit.',
  },
  {
    id: 'gm45',
    title: 'Skechers Go Walk Slip-Ons',
    category: 'Shoes',
    condition: 'Excellent',
    price: 8900,
    image: '/images/shoes/skechers-go-walk-slip-ons.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-08-07T17:00:00Z',
    description:
      'Ultra-comfortable slip-on shoes, barely used, perfect for daily walks.',
  },
  {
    id: 'gm46',
    title: '2 BHK Apartment, Whitefield',
    category: 'Real Estate',
    condition: 'Excellent',
    price: 25000000,
    image: '/images/real-estate/2-bhk-apartment-whitefield.jpg',
    seller: 'Pune Mobile World',
    location: 'Pune, MH',
    createdAt: '2024-06-28T08:45:00Z',
    description:
      'Spacious 2 BHK apartment in a gated community with modern amenities, ready to move in.',
  },
  {
    id: 'gm47',
    title: '3 BHK Independent Villa, Jaipur',
    category: 'Real Estate',
    condition: 'Fine',
    price: 35000000,
    image: '/images/real-estate/3-bhk-independent-villa-jaipur.jpg',
    seller: 'Delhi Wheels & More',
    location: 'New Delhi, DL',
    createdAt: '2024-10-20T06:45:00Z',
    description:
      'Well-designed villa with private garden, covered parking, and modern interiors.',
  },
  {
    id: 'gm48',
    title: 'Studio Flat, Koramangala',
    category: 'Real Estate',
    condition: 'Good',
    price: 35000000,
    image: '/images/real-estate/studio-flat-koramangala.jpg',
    seller: 'Kochi Jewels & Gems',
    location: 'Kochi, KL',
    createdAt: '2024-09-17T22:20:00Z',
    description:
      'Compact studio flat perfect for singles or working professionals, close to tech parks.',
  },
  {
    id: 'gm49',
    title: '4 BHK Farmhouse, Lonavala',
    category: 'Real Estate',
    condition: 'Excellent',
    price: 25000000,
    image: '/images/real-estate/4-bhk-farmhouse-lonavala.jpg',
    seller: 'Indore Home Estates',
    location: 'Indore, MP',
    createdAt: '2024-06-08T06:00:00Z',
    description:
      'Weekend getaway farmhouse with landscaped garden and swimming pool, fully furnished.',
  },
  {
    id: 'gm50',
    title: 'Residential Plot, Sector 150 Noida',
    category: 'Real Estate',
    condition: 'Fine',
    price: 25000000,
    image: '/images/real-estate/residential-plot-sector-150-noida.jpg',
    seller: 'Kochi Jewels & Gems',
    location: 'Kochi, KL',
    createdAt: '2024-06-08T14:45:00Z',
    description:
      'Clear-titled residential plot in a developing sector, ideal for custom home construction.',
  },
  {
    id: 'gm51',
    title: '2 BHK Sea-View Flat, Mumbai',
    category: 'Real Estate',
    condition: 'Excellent',
    price: 25000000,
    image: '/images/real-estate/2-bhk-sea-view-flat-mumbai.jpg',
    seller: 'Lucknow Auto Point',
    location: 'Lucknow, UP',
    createdAt: '2024-09-15T13:20:00Z',
    description:
      'Premium sea-facing apartment with modern fittings, close to local transit.',
  },
  {
    id: 'gm52',
    title: '3 BHK Duplex, Bandra',
    category: 'Real Estate',
    condition: 'Good',
    price: 18000000,
    image: '/images/real-estate/3-bhk-duplex-bandra.jpg',
    seller: 'Kolkata Shoe Gallery',
    location: 'Kolkata, WB',
    createdAt: '2024-09-08T08:00:00Z',
    description:
      'Well-maintained duplex with ample natural light and dedicated parking space.',
  },
];